services:
  - type: web
    name: explainable-dbms-frontend
    env: static
    buildCommand: cd src/explainable_dbms/xai_dbms_frontend && npm install && npm run build
    staticPublishPath: src/explainable_dbms/xai_dbms_frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
